name: R lintr

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  lintr:
    name: Run lintr
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install R
        run: |
          sudo apt-get update
          sudo apt-get install -y r-base

      - name: Install lintr
        run: |
          R_LIBS_USER="${HOME}/.local/lib/R/site-library"
          mkdir -p "${R_LIBS_USER}"
          R -e "install.packages('remotes', repos = 'https://cloud.r-project.org'); remotes::install_github('r-lib/lintr')"

      - name: Run lintr and generate SARIF
        run: |
          R_LIBS_USER="${HOME}/.local/lib/R/site-library" Rscript -e "
            dirs <- c('R', 'inst', 'man', 'tests', 'tools')
            lints <- unlist(lapply(dirs, function(d) if (dir.exists(d)) lintr::lint_dir(d) else list()), recursive = FALSE)
            if (length(lints) > 0) {
              lintr::sarif_output(lints, 'lintr.sarif', pkg_path = '.')
            } else {
              cat('No lint issues found.\n')
            }
          "
        continue-on-error: true

      - name: Upload SARIF report
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: lintr.sarif
