name: Lintr

on:
  push:
    branches: [main]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  lintr:
    name: Run lintr on R package
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install dependencies
      run: |
        install.packages("lintr")
      shell: Rscript {0}

    - name: Run lintr
      run: |
        lint_results <- lintr::lint_package(config = ".lintr.yaml")
        print(lint_results)
        if (length(lint_results) > 0) {
          stop("❌ lintr found issues. Failing the job.")
        } else {
          message("✅ No linting issues found.")
        }
      shell: Rscript {0}
