name: "lintr"

on:
  push:
    branches: [main]
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 0 * * 0'  # Weekly scan

jobs:
  analyze:
    name: CodeQL Analysis + R lintr
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'cpp', 'python' ]  # Add other supported CodeQL languages here

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Set up CodeQL
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}

    - name: Autobuild
      uses: github/codeql-action/autobuild@v3

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3

    # --- Start of lintr integration ---
    - name: Setup R
      uses: r-lib/actions/setup-r@v2

    - name: Install lintr
      run: |
        install.packages("lintr")
      shell: Rscript {0}

    - name: Run lintr
      run: |
        lint_results <- lintr::lint_dir(config = ".lintr.yaml")
        print(lint_results)
        if (length(lint_results) > 0) {
          stop("lintr found issues. Failing the job.")
        }
      shell: Rscript {0}
    # --- End of lintr integration ---
